name: OnStar2MQTT HASS Add-On
version: "1.5.9" 
slug: onstar2mqtt-addon
description: OnStar data inttegration into Home Assistant via MQTT
startup: application
boot: auto
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
url: 'https://github.com/dannysporea/onstar2mqtt-addon'
#image: 'michaelwoods/onstar2mqtt'
services:
  - 'mqtt:need'
init: false
options:
  ONSTAR_DEVICEID: ''
  ONSTAR_VIN: ''
  ONSTAR_USERNAME: ''
  ONSTAR_PASSWORD: '' 
  ONSTAR_PIN: ''
  ONSTAR_URL: 'https://api.gm.com'
  ONSTAR_REFRESH: 1800000
  MQTT_HOST: ''
  MQTT_USERNAME: ''
  MQTT_PASSWORD: '' 
schema:
  ONSTAR_DEVICEID: str
  ONSTAR_VIN: str
  ONSTAR_USERNAME: str
  ONSTAR_PASSWORD: password
  ONSTAR_PIN: password
  ONSTAR_URL: str
  ONSTAR_REFRESH: int
  MQTT_HOST: str
  MQTT_USERNAME: str
  MQTT_PASSWORD: password
